---

- name: 'Provision Image'
  hosts: packer
  become: true

  tasks:

    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present

    # Test localhost commands work as expected
    - name: Create a test file
      ansible.builtin.copy:
        content: My test data
        dest: /tmp/mytestfile
        owner: "{{ lookup('ansible.builtin.env', 'USER') | default('nobody', True) }}"
        mode: '0640'
      delegate_to: localhost
